# render.yaml
version: 1
services:
  - type: web
    name: iq-option-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
    envVars:
      # TOKEN de tu bot de Telegram
      - key: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
      # CLAVE SECRETA para las sesiones de Flask (¡GENERA UNA CLAVE FUERTE Y ÚNICA!)
      - key: FLASK_SECRET_KEY
        
        
